{{- if .Values.global.jaeger.enabled }}
---
apiVersion: v1
kind: configMap
metadata:
  name: hosts-config
data:
  hosts: |-
    {{- range .Values.global.jaegger.querry.ingress.hosts }}
    - {{ . }}
    {{- end }}
