{{- if .Values.storage.enabled }}
  {{- if .Values.ezdrpApi.active }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.ezdrpApi.moduleName }}-epuap-storage
spec:
  accessModes:
    - {{ .Values.ezdrpApi.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ezdrpApi.persistence.size }}Gi
  storageClassName: {{ .Values.ezdrpApi.persistence.storageClass }}
status:
  accessModes:
    - {{ .Values.ezdrpApi.persistence.accessMode }}
  capacity:
    storage: {{ .Values.ezdrpApi.persistence.size }}Gi
  {{- end }}
{{- end }}