global:
  elastic:
    enabled: true
  istiod:
    enabled: true
  jaeger:
    enabled: true
  rancher-monitoring:
    enabled: false

elastic:
  eckElasticsearch:
    params:
      ingress:
        hostname: ""
      storageclass: ""

  eckPackageRegistry:
    params:
      ingress:
        hostname: ""

  eckKibana:
    params:
      ingress:
        hostname: ""

  eckApm:
    params:
      ingress:
        hostname: ""

  eckFleet:
    params:
      ingress:
        hostname: ""



jaeger:
  agent:
    service:
      type: ClusterIP
      zipkinThriftPort: 5775
      binaryPort: 6832
      compactPort: 6831
      samplingPort: 5778
  collector:
    service:
      grpc:
        port: 14250
      zipkin:
        port: 9411
  query:
    service:
      port: 16686
    ingress:
      enabled: true

istiod:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 99
      zipkin:
        address: ""
