{{- if .Values.procesowosc.active }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.procesowosc.moduleName }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.procesowosc.moduleName }}
    role: backend
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.procesowosc.moduleName }}
      role: backend
      environment: {{ .Values.environment }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.procesowosc.moduleName }}
        role: backend
        environment: {{ .Values.environment }}
    spec:
      {{- if and (.Values.affinity.nodeAffinitySelector.name) (.Values.affinity.nodeAffinitySelector.value) }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.affinity.nodeAffinitySelector.name }}
                    operator: In
                    values:
                      - {{ .Values.affinity.nodeAffinitySelector.value | quote }}
      {{- end }}
      containers:
        - image: {{ .Values.imageCredentials.registryDomain }}/ezdrp-{{ .Values.procesowosc.moduleName }}:1.0
          env:
          - name: EZD_DOMAIN
            value: {{ .Values.domainInfo.name }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: {{ .Values.procesowosc.redinessDelay }}
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.procesowosc.port }}
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 4
            initialDelaySeconds: {{ .Values.procesowosc.livenessDelay }}
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.procesowosc.port }}
            timeoutSeconds: 1
          name: {{ .Values.procesowosc.moduleName }}
          startupProbe:
            failureThreshold: 50
            initialDelaySeconds: {{ .Values.procesowosc.startupDelay }}
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.procesowosc.port }}
            timeoutSeconds: 1
          {{- if or (.Values.procesowosc.resources.limits.cpu) (.Values.procesowosc.resources.limits.memory) (.Values.procesowosc.resources.requests.cpu) (.Values.procesowosc.resources.requests.memory) }}
          resources:
            {{- if or (.Values.procesowosc.resources.limits.cpu) (.Values.procesowosc.resources.limits.memory) }}
            limits:
              {{- if .Values.procesowosc.resources.limits.cpu }}
              cpu: {{ .Values.procesowosc.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.procesowosc.resources.limits.memory }}
              memory: {{ .Values.procesowosc.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if or (.Values.procesowosc.resources.requests.cpu) (.Values.procesowosc.resources.requests.memory) }}
            requests:
              {{- if .Values.procesowosc.resources.requests.cpu }}
              cpu: {{ .Values.procesowosc.resources.requests.cpu }}
              {{- end }}
              {{- if .Values.procesowosc.resources.requests.memory }}
              memory: {{ .Values.procesowosc.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}