{{- if .Values.ssoApigateway.active }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ssoApigateway.moduleName }}
  labels:
    run: {{ .Values.ssoApigateway.moduleName }}
spec:
  type: {{ .Values.ssoApigateway.service.type }}
  ports:
    - name: {{ .Values.ssoApigateway.moduleName }}
      port: {{ .Values.ssoApigateway.port }}
      targetPort: {{ .Values.ssoApigateway.port }}
      protocol: TCP
    - name: "{{ .Values.ssoApigateway.moduleName }}-admin"
      port: {{ .Values.ssoApigateway.portAdmin }}
      targetPort: {{ .Values.ssoApigateway.portAdmin }}
      protocol: TCP
    - name: "{{ .Values.ssoApigateway.moduleName }}-cache"
      port: {{ .Values.ssoApigateway.portCache }}
      targetPort: {{ .Values.ssoApigateway.portCache }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.ssoApigateway.moduleName }}
  sessionAffinity: None
{{- end }}