apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ezdrp-rolebindng
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
subjects:
- kind: User
  name: ezdrp
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ezdrp-role
  apiGroup: rbac.authorization.k8s.io