{{- if .Values.wpeRest.active }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wpeRest.moduleName }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.wpeRest.moduleName }}
    role: backend
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.wpeRest.moduleName }}
      role: backend
      environment: {{ .Values.environment }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.wpeRest.moduleName }}
        role: backend
        environment: {{ .Values.environment }}
    spec:
      {{- if and (.Values.affinity.nodeAffinitySelector.name) (.Values.affinity.nodeAffinitySelector.value) }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.affinity.nodeAffinitySelector.name }}
                    operator: In
                    values:
                      - {{ .Values.affinity.nodeAffinitySelector.value | quote }}
      {{- end }}
      containers:
        - image: {{ .Values.imageCredentials.registryDomain }}/{{ .Values.wpeRest.image.name }}:{{ .Values.wpeRest.image.version }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: http://{{ .Values.wpeRest.moduleName }}/info
              port: {{ .Values.wpeRest.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.wpeRest.livenessDelay }}
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: {{ .Values.wpeRest.moduleName }}
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: http://{{ .Values.wpeRest.moduleName }}/info
              port: {{ .Values.wpeRest.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.wpeRest.redinessDelay }}
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          {{- if or (.Values.wpeRest.resources.limits.cpu) (.Values.wpeRest.resources.limits.memory) (.Values.wpeRest.resources.requests.cpu) (.Values.wpeRest.resources.requests.memory) }}
          resources:
            {{- if or (.Values.wpeRest.resources.limits.cpu) (.Values.wpeRest.resources.limits.memory) }}
            limits:
              {{- if .Values.wpeRest.resources.limits.cpu }}
              cpu: {{ .Values.wpeRest.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.wpeRest.resources.limits.memory }}
              memory: {{ .Values.wpeRest.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if or (.Values.wpeRest.resources.requests.cpu) (.Values.wpeRest.resources.requests.memory) }}
            requests:
              {{- if .Values.wpeRest.resources.requests.cpu }}
              cpu: {{ .Values.wpeRest.resources.requests.cpu }}
              {{- end }}
              {{- if .Values.wpeRest.resources.requests.memory }}
              memory: {{ .Values.wpeRest.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /data
              name: {{ .Values.wpeRest.moduleName }}-storage
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      {{- if or ( .Release.IsInstall ) ( .Values.storage.force_chown ) }}
      initContainers:
        - name: volume-owner-hack
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 501:501 /data
          volumeMounts:
          - name: {{ .Values.wpeRest.moduleName }}-storage
            mountPath: /data
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ .Values.wpeRest.moduleName }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.wpeRest.moduleName }}-storage
      serviceAccount: ezdrp
      serviceAccountName: ezdrp
{{ end }}