{{ if ( .Values.global.rabbitmq.deploy ) }}
apiVersion: v1
kind: Secret
metadata:
  name: "credentials-{{ include "ezd-backend.rabbitmqConfig.fullname" . }}"
  labels:
    {{- include "ezd-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  default_user.conf: |
    default_user = {{ include "ezd-backend.username" .Values.global.rabbitmqConfig.auth.username }}
    default_pass = {{ include "ezd-backend.password" .Values.global.rabbitmqConfig.auth.password }}
  username: {{ include "ezd-backend.username" .Values.global.rabbitmqConfig.auth.username }}
  password: {{ include "ezd-backend.password" .Values.global.rabbitmqConfig.auth.password }}
  port: {{ default ( "5672" ) | quote }}
  provider: {{ default ( "rabbitmq" ) }}
  type: {{ default ( "rabbitmq" ) }}
  host: {{ printf "%s.%s.%s" ( include "ezd-backend.rabbitmqConfig.fullname" . ) .Release.Namespace "svc" }}
{{ end }}
