# Default values for ezd-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  rabbitmqConfig:
    auth:
      username: "ezdrpadmin"
      password: "postgrespostgres"
  postgresqlConfig:
    auth:
      admPassword: "postgrespostgres"
      appPassword: "postgresapp"
  redisConfig:
    auth:
      password: "postgrespostgres"

ezdBackend:
  rabbitmqConfig:
      persistence:
        storageClassName: longhorn
  redisConfig:
      customConfig:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
  postgresqlConfig:
    customConfig:
      storage:
        storageClass: longhorn
      walStorage:
        storageClass: longhorn

#nask-ezdrp-ha:
cloudadmin:
  relationaldb:
    connectiontype:
      archiwum: POSTGRESQL
      ezdrp: POSTGRESQL
      ezdrpodczyt: POSTGRESQL
      kuip: POSTGRESQL
domainInfo:
  cert_info: true
  cert_name: ezdrp-cert
  name: ezd.dbo.test
email:
  active: false
ezdrpApi:
  persistence:
    storageClass: longhorn
filerepository:
  persistence:
    storageClass: longhorn
    filerepoStorageType: "S1"
    s3:
      host: "https://api.obj0.dbo.test"
      port: "9000"
      access_key: "minioadmin"
      secret_key: "minioadmin"
      tls: "true"
      bucketname: "ezdrp2024"
    ezdpuwmigration:
      enabled: false
      dataPath: "/EZD_PUW/data"
      metaPath: "/EZD_PUW/meta"
      storageClass: ""
      size:
      accessMode: ReadWriteOnce
rabbitExt:
  port: 5672
redisAppendExt:
  port: 6379
redisExt:
  port: 6379
ssoIdentityServer:
  persistence:
    storageClass: longhorn
wpeRest:
  persistence:
    storageClass: longhorn
