global:
  elastic:
    enabled: false
  istiod:
    enabled: true
  jaeger:
    enabled: true



jaeger:
  agent:
    extraEnv: []
    service:
      type: ClusterIP
      zipkinThriftPort: 5775
      binaryPort: 6832
      compactPort: 6831
      samplingPort: 5778
  collector:
    service:
      grpc:
        port: 14250
      zipkin:
        port: 9411
  query:
    basePath: /jaeger
    service:
      port: 16686
    ingress:
      enabled: false
istiod:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 99
