{{- if .Values.procesowosc.active }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.procesowosc.moduleName }}
  labels:
    run: {{ .Values.procesowosc.moduleName }}
spec:
  type: {{ .Values.procesowosc.service.type }}
  ports:
    - name: {{ .Values.procesowosc.moduleName }}
      port: {{ .Values.procesowosc.port }}
      targetPort: {{ .Values.procesowosc.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.procesowosc.moduleName }}
  sessionAffinity: None
{{ end }}