{{- if .Values.kuipWeb.active }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kuipWeb.moduleName }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.kuipWeb.moduleName }}
    role: frontend
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.kuipWeb.moduleName }}
      role: frontend
      environment: {{ .Values.environment }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.kuipWeb.moduleName }}
        role: frontend
        environment: {{ .Values.environment }}
    spec:
      {{- if and (.Values.affinity.nodeAffinitySelector.name) (.Values.affinity.nodeAffinitySelector.value) }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.affinity.nodeAffinitySelector.name }}
                    operator: In
                    values:
                      - {{ .Values.affinity.nodeAffinitySelector.value | quote }}
      {{- end }}
      containers:
        - image: {{ .Values.imageCredentials.registryDomain }}/{{ .Values.kuipWeb.image.name }}:{{ .Values.kuipWeb.image.version }}
          env:
            - name: REACT_APP_PROD
              value: {{ .Values.kuipWeb.appProd | quote }}
            - name: EZD_DOMAIN
              value: {{ .Values.domainInfo.name }}
            - name: EZD_BASE_WEB_NAME
              value: /
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 4
            initialDelaySeconds: {{ .Values.kuipWeb.livenessDelay }}
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.kuipWeb.port }}
            timeoutSeconds: 1
          name: {{ .Values.kuipWeb.moduleName }}
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: {{ .Values.kuipWeb.redinessDelay }}
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.kuipWeb.port }}
            timeoutSeconds: 1
          {{- if or (.Values.kuipWeb.resources.limits.cpu) (.Values.kuipWeb.resources.limits.memory) (.Values.kuipWeb.resources.requests.cpu) (.Values.kuipWeb.resources.requests.memory) }}
          resources:
            {{- if or (.Values.kuipWeb.resources.limits.cpu) (.Values.kuipWeb.resources.limits.memory) }}
            limits:
              {{- if .Values.kuipWeb.resources.limits.cpu }}
              cpu: {{ .Values.kuipWeb.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.kuipWeb.resources.limits.memory }}
              memory: {{ .Values.kuipWeb.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if or (.Values.kuipWeb.resources.requests.cpu) (.Values.kuipWeb.resources.requests.memory) }}
            requests:
              {{- if .Values.kuipWeb.resources.requests.cpu }}
              cpu: {{ .Values.kuipWeb.resources.requests.cpu }}
              {{- end }}
              {{- if .Values.kuipWeb.resources.requests.memory }}
              memory: {{ .Values.kuipWeb.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: ezdrp
      serviceAccountName: ezdrp
{{ end }}