{{- if .Values.integratorApi.active }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      gzip on;
      gzip_vary off;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_types *;
      proxy_set_header X-Origin $http_origin;
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "240"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ .Values.integratorApi.moduleName }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.integratorApi.moduleName }}.{{ .Values.domainInfo.name }}
    http:
      paths:
      - path: /(.+)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ssoApigateway.moduleName }}
            port:
              number: {{ .Values.ssoApigateway.port }}
{{- if .Values.domainInfo.cert_info }}
  tls:
  - hosts:
    - {{ .Values.integratorApi.moduleName }}.{{ .Values.domainInfo.name }}
    secretName: {{ .Values.domainInfo.cert_name }}
{{- end }}
{{- end }}