{{- if .Values.integratorApi.active }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.integratorApi.moduleName }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.integratorApi.moduleName }}
    role: backend
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.integratorApi.moduleName }}
      role: backend
      environment: {{ .Values.environment }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.integratorApi.moduleName }}
        role: backend
        environment: {{ .Values.environment }}
    spec:
      {{- if and (.Values.affinity.nodeAffinitySelector.name) (.Values.affinity.nodeAffinitySelector.value) }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.affinity.nodeAffinitySelector.name }}
                    operator: In
                    values:
                      - {{ .Values.affinity.nodeAffinitySelector.value | quote }}
      {{- end }}
      containers:
        - image: {{ .Values.imageCredentials.registryDomain }}/{{ .Values.integratorApi.image.name }}:{{ .Values.integratorApi.image.version }}
          env:
            - name: ICE_CLOUD_ADMIN_URL
              value: "http://{{ .Values.cloudadmin.moduleName }}:{{ .Values.cloudadmin.port }}"
            - name: ICE_CONFIG
              value: {{ .Values.integratorApi.cloudadmin.configname }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 4
            initialDelaySeconds: {{ .Values.integratorApi.livenessDelay }}
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.integratorApi.port }}
            timeoutSeconds: 1
          name: {{ .Values.integratorApi.moduleName }}
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: {{ .Values.integratorApi.redinessDelay }}
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.integratorApi.port }}
            timeoutSeconds: 1
          {{- if or (.Values.integratorApi.resources.limits.cpu) (.Values.integratorApi.resources.limits.memory) (.Values.integratorApi.resources.requests.cpu) (.Values.integratorApi.resources.requests.memory) }}
          resources:
            {{- if or (.Values.integratorApi.resources.limits.cpu) (.Values.integratorApi.resources.limits.memory) }}
            limits:
              {{- if .Values.integratorApi.resources.limits.cpu }}
              cpu: {{ .Values.integratorApi.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.integratorApi.resources.limits.memory }}
              memory: {{ .Values.integratorApi.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if or (.Values.integratorApi.resources.requests.cpu) (.Values.integratorApi.resources.requests.memory) }}
            requests:
              {{- if .Values.integratorApi.resources.requests.cpu }}
              cpu: {{ .Values.integratorApi.resources.requests.cpu }}
              {{- end }}
              {{- if .Values.integratorApi.resources.requests.memory }}
              memory: {{ .Values.integratorApi.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - |
              /docker-entrypoint.sh wait_for ezdrpapi:${EZDRPAPI_HOST}:${EZDRPAPI_PORT}
          env:
            - name: EZDRPAPI_HOST
              value: {{ .Values.ezdrpApi.moduleName }}
            - name: EZDRPAPI_PORT
              value: {{ .Values.ezdrpApi.port | quote }}
          image: {{ .Values.waitfor.image.registry }}/{{ .Values.waitfor.image.name }}:{{ .Values.waitfor.image.version }}
          imagePullPolicy: IfNotPresent
          name: waitfor
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: ezdrp
      serviceAccountName: ezdrp
{{ end }}